services:
  app:
    build: .
    image: places:1.0.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["/app/.venv/bin/fastapi", "run", "main.py", "--port", "8000", "--host", "0.0.0.0"]

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata: